### ISSUE TITLE
Coordinates definition in BusI Model

### ISSUE THREAD

**Issue by eniovianna** [PauloRadatz/py_dss_interface#11]
Context: Method called **bus_coord_defined()** in **BusI Model.**
@PauloRadatz Is there a way to create artificial coordinates? I know a possible algorithm to generate this, if this is a desirable feature just say and I will implement this, otherwise just remove that TODO and push.

**Comment by PauloRadatz** [comment]
I would say it is not necessary since most of the feeders we use have coords.
