### ISSUE TITLE
Methods to check param type

### ISSUE THREAD

**Issue by rodolfoplondero** [PauloRadatz/py_dss_interface#22]
@eniovianna Methods `check_int_param` and `check_float_param` in `Base.py` are returning zero when the correct type is received as param. Probably the same happens with `check_string_param`

#22

**Comment by eniovianna** [comment]
Solved in this [commit](https://github.com/PauloRadatz/py_dss_interface/commit/c0faf5eb12d91aeccde7ddf59728e8304bffa6bf)
