### ISSUE TITLE
Names of Elements

### ISSUE THREAD

**Issue by binaysdl** [PauloRadatz/py_dss_interface#49]
Hi Paulo,

Seems to have missing the following functions.
dss.reactors_all_names()
dss.storage_all_names()

Also, transformer is the only one with capital N.
dss.transformer_all_Names()

**Comment by eniovianna** [comment]
Thanks for your advice @binaysdl 
Solved in [commit](https://github.com/PauloRadatz/py_dss_interface/pull/89/commits/9230d1273226dd7f434a935c031dad2180393247)
